steps:
  # Debug step
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Debug: DOPPLER_TOKEN available: ${_DOPPLER_TOKEN:0:5}..."
    secretEnv: ["_DOPPLER_TOKEN"]

  # Build step with correct secret handling
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          --build-arg "DOPPLER_TOKEN=$$_DOPPLER_TOKEN" \
          --build-arg "ENVIRONMENT=$$_ENVIRONMENT" \
          -t gcr.io/pin-mastery/f3-nation-map \
          -f apps/map/Dockerfile \
          .
    secretEnv: ["_DOPPLER_TOKEN"]

  # Push step
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/pin-mastery/f3-nation-map"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "f3-2" # Name for your Cloud Run service
      - "--image"
      - "gcr.io/pin-mastery/f3-nation-map" # The image you built
      - "--region"
      - "us-central1" # e.g., us-central1
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/233824588998/secrets/DOPPLER_TOKEN/versions/2
      env: "_DOPPLER_TOKEN"
