#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# generate-env.sh — Pull staging secrets from GCP and generate .env for local dev
# =============================================================================
#
# Usage:
#   bash scripts/generate-env.sh          # Generate .env from staging secrets
#   bash scripts/generate-env.sh --dry-run # Show what would be generated
#
# Prerequisites:
#   - gcloud CLI authenticated (gcloud auth login)
#   - Access to f3-authentication-staging GCP project
#
# This script:
#   1. Pulls secrets from GCP Secret Manager (staging project only — never prod)
#   2. Generates a root .env with sane local-dev defaults
#   3. Symlinks .env.local into each app directory
#
# Compatible with macOS bash 3.2+ (no associative arrays or bash 4+ features).
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Always pull from staging — never production
GCP_PROJECT="f3-authentication-staging"

# --- Parse flags -------------------------------------------------------------

DRY_RUN=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "Unknown argument: $1"; echo "Usage: $0 [--dry-run]"; exit 1 ;;
  esac
done

# --- Preflight checks --------------------------------------------------------

if ! command -v gcloud &>/dev/null; then
  echo "Error: gcloud CLI not found. Install: brew install google-cloud-sdk"
  exit 1
fi

if ! gcloud auth print-identity-token &>/dev/null 2>&1; then
  echo "Error: Not authenticated with GCP. Run: gcloud auth login"
  exit 1
fi

if ! gcloud secrets list --project="$GCP_PROJECT" --limit=1 &>/dev/null 2>&1; then
  echo "Error: Cannot access secrets in project '$GCP_PROJECT'."
  echo "Ask a team lead to grant you 'Secret Manager Secret Accessor' role."
  exit 1
fi

echo "Pulling secrets from GCP project: $GCP_PROJECT"
echo ""

# --- Pull secrets from GCP (no associative arrays — macOS bash 3.2 compat) ---

pull_secret() {
  local gcp_name="$1"
  gcloud secrets versions access latest \
    --secret="$gcp_name" \
    --project="$GCP_PROJECT" 2>/dev/null || echo ""
}

SECRET_DATABASE_USER=$(pull_secret "database-user")
SECRET_DATABASE_PASSWORD=$(pull_secret "database-password")
SECRET_DATABASE_NAME=$(pull_secret "database-name")
SECRET_AUTH_SECRET=$(pull_secret "auth-secret")
SECRET_AUTH_JWT_PRIVATE_KEY=$(pull_secret "auth-jwt-private-key")
SECRET_API_KEY=$(pull_secret "api-key")
SECRET_SENDGRID_API_KEY=$(pull_secret "sendgrid-api-key")
SECRET_GOOGLE_MAPS_API_KEY=$(pull_secret "google-maps-api-key")
SECRET_GOOGLE_LOGO_BUCKET_PRIVATE_KEY=$(pull_secret "google-logo-bucket-private-key")
SECRET_GOOGLE_LOGO_BUCKET_CLIENT_EMAIL=$(pull_secret "google-logo-bucket-client-email")
SECRET_GOOGLE_LOGO_BUCKET_BUCKET_NAME=$(pull_secret "google-logo-bucket-bucket-name")

# Log what we got
for name in DATABASE_USER DATABASE_PASSWORD DATABASE_NAME AUTH_SECRET AUTH_JWT_PRIVATE_KEY API_KEY GOOGLE_MAPS_API_KEY GOOGLE_LOGO_BUCKET_PRIVATE_KEY GOOGLE_LOGO_BUCKET_CLIENT_EMAIL GOOGLE_LOGO_BUCKET_BUCKET_NAME; do
  var="SECRET_$name"
  if [[ -n "${!var:-}" ]]; then
    echo "  OK: $name"
  else
    echo "  WARN: $name (not found)"
  fi
done
# EMAIL_SERVER is derived from the sendgrid-api-key secret
if [[ -n "${SECRET_SENDGRID_API_KEY:-}" ]]; then
  echo "  OK: EMAIL_SERVER"
else
  echo "  WARN: EMAIL_SERVER (sendgrid-api-key not found)"
fi

echo ""

# --- Construct derived values ------------------------------------------------

DB_USER="${SECRET_DATABASE_USER:-postgres}"
DB_PASS="${SECRET_DATABASE_PASSWORD:-}"
DB_NAME="${SECRET_DATABASE_NAME:-f3data}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5433/${DB_NAME}"
TEST_DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5433/${DB_NAME}_test"

if [[ -n "${SECRET_SENDGRID_API_KEY:-}" ]]; then
  EMAIL_SERVER="smtp://apikey:${SECRET_SENDGRID_API_KEY}@smtp.sendgrid.net:587"
else
  EMAIL_SERVER=""
fi

if [[ -z "${EMAIL_SERVER}" ]]; then
  echo "  ERROR: EMAIL_SERVER could not be resolved (sendgrid-api-key secret not found)"
  echo "  The auth app requires EMAIL_SERVER. Set the GCP secret and re-run."
  exit 1
fi

if [[ -z "${SECRET_GOOGLE_MAPS_API_KEY:-}" ]]; then
  echo "  ERROR: F3_GOOGLE_API_KEY could not be resolved (google-maps-api-key secret not found)"
  echo "  The map app requires a non-empty F3_GOOGLE_API_KEY. Set the GCP secret and re-run."
  exit 1
fi

SUPER_ADMIN_API_KEY="${SECRET_API_KEY:-}"

# --- Generate .env content ----------------------------------------------------

generate_env() {
  cat << ENVEOF
# =============================================================================
# F3 Nation — Local Development Environment
# =============================================================================
# Auto-generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source: GCP project '$GCP_PROJECT' (staging — never production)
# =============================================================================

NODE_ENV=development

# -- Local dev server URLs --
NEXT_PUBLIC_ADMIN_URL=http://localhost:3002
NEXT_PUBLIC_API_URL=http://localhost:3001
NEXT_PUBLIC_MAP_URL=http://localhost:3000
NEXT_PUBLIC_AUTH_URL=http://localhost:3004
NEXT_PUBLIC_CHANNEL=local

# -- Map app server runtime vars (read at request time, not the NEXT_PUBLIC_* ones) --
# The map app validates these F3_* names in apps/map/src/env.ts and does NOT
# read the NEXT_PUBLIC_* equivalents above. Without them, env validation fails
# on `pnpm dev`.
F3_ADMIN_URL=http://localhost:3002
F3_API_BASE_URL=http://localhost:3001
F3_MAP_BASE_URL=http://localhost:3000
F3_CHANNEL=local

# F3_MAP_API_KEY authenticates in-process router calls during static generation
# (\`next build\`/SSG). Optional in dev, but required for builds. Must match a key
# in the local DB — \`pnpm db:seed:local\` inserts "local-map-key".
F3_MAP_API_KEY=local-map-key

# -- Google Maps API key (from GCP Secret Manager) --
# In production, this key is set via Cloud Run environment configuration.
# GCP Secret Manager stores the canonical value so this script can pull it
# automatically, keeping the local dev setup as frictionless as possible.
NEXT_PUBLIC_GOOGLE_API_KEY=${SECRET_GOOGLE_MAPS_API_KEY:-}
F3_GOOGLE_API_KEY=${SECRET_GOOGLE_MAPS_API_KEY:-}

# -- Email --
EMAIL_FROM=noreply@f3nation.com
EMAIL_ADMIN_DESTINATIONS=dev@f3nation.com

# -- Notifications (disabled locally) --
# NOTIFY_WEBHOOK_URLS_COMMA_SEPARATED=

# -- Database credentials (from GCP Secret Manager) --
DATABASE_URL=$DATABASE_URL
TEST_DATABASE_URL=$TEST_DATABASE_URL

# -- Auth app DB fields (parsed individually, not from DATABASE_URL) --
DATABASE_HOST=localhost
DATABASE_USER=$DB_USER
DATABASE_PASSWORD=$DB_PASS
DATABASE_NAME=$DB_NAME

# -- Secrets (from GCP Secret Manager) --
AUTH_SECRET=${SECRET_AUTH_SECRET:-}
API_KEY=${SECRET_API_KEY:-}
SUPER_ADMIN_API_KEY=$SUPER_ADMIN_API_KEY
EMAIL_SERVER=$EMAIL_SERVER

# -- Auth JWT private key (PEM format, newlines escaped) --
ENVEOF

  # Handle JWT key separately (may contain newlines)
  jwt_key="${SECRET_AUTH_JWT_PRIVATE_KEY:-}"
  if [[ -n "$jwt_key" ]]; then
    escaped_key=$(printf '%s' "$jwt_key" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
    echo "AUTH_JWT_PRIVATE_KEY=\"$escaped_key\""
  else
    echo "# AUTH_JWT_PRIVATE_KEY=  (not found in GCP)"
  fi

  # Handle GCS private key separately (may contain newlines)
  gcs_key="${SECRET_GOOGLE_LOGO_BUCKET_PRIVATE_KEY:-}"
  echo ""
  echo "# -- Google Cloud Storage (from GCP Secret Manager) --"
  if [[ -n "$gcs_key" ]]; then
    escaped_gcs_key=$(printf '%s' "$gcs_key" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
    echo "GOOGLE_LOGO_BUCKET_PRIVATE_KEY=\"$escaped_gcs_key\""
  else
    echo "# GOOGLE_LOGO_BUCKET_PRIVATE_KEY=  (not found in GCP)"
  fi
  echo "GOOGLE_LOGO_BUCKET_CLIENT_EMAIL=${SECRET_GOOGLE_LOGO_BUCKET_CLIENT_EMAIL:-}"
  echo "GOOGLE_LOGO_BUCKET_BUCKET_NAME=${SECRET_GOOGLE_LOGO_BUCKET_BUCKET_NAME:-}"

  cat << 'ENVEOF2'

# -- Auth app URLs --
NEXTAUTH_URL=http://localhost:3004
ENVEOF2
}

# --- Write or preview ---------------------------------------------------------

ENV_FILE="$REPO_ROOT/.env"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "DRY RUN — would generate $ENV_FILE with:"
  echo "---"
  generate_env
  echo "---"
  echo ""
  echo "Would create symlinks:"
  for app in api map auth; do
    echo "  apps/$app/.env.local → ../../.env"
  done
  echo ""
  echo "Dry run complete — no files written."
  exit 0
fi

generate_env > "$ENV_FILE"
echo "Generated: $ENV_FILE"
echo ""

# --- Symlink into app directories --------------------------------------------

echo "Creating symlinks:"
for app in api map auth; do
  app_dir="$REPO_ROOT/apps/$app"
  link_path="$app_dir/.env.local"

  if [[ ! -d "$app_dir" ]]; then
    echo "  SKIP: apps/$app (directory not found)"
    continue
  fi

  # Back up existing .env.local if it's not already our symlink
  if [[ -e "$link_path" && ! -L "$link_path" ]]; then
    echo "  BACKUP: apps/$app/.env.local → apps/$app/.env.local.bak"
    mv "$link_path" "${link_path}.bak"
  fi

  ln -sf "../../.env" "$link_path"
  echo "  OK: apps/$app/.env.local → ../../.env"
done

echo ""
echo "Done! Local dev environment is ready."
echo ""
echo "Next steps:"
echo "  1. Start the Cloud SQL proxy:  pnpm db:proxy"
echo "  2. Run migrations:             pnpm db:migrate"
echo "  3. Start dev servers:           pnpm dev"
echo ""
echo "All apps share the root .env via symlinks."
echo "To override a specific app, edit apps/<app>/.env.local directly (break the symlink)."
